name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
      - 
        name: Git checkout
        uses: actions/checkout@v3
      - 
        name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - 
        name: Upload coverage
        uses: codecov/codecov-action@v1